### ISSUE TITLE
Diseñar de mockup para la Interfaz de Registro y Login

### ISSUE THREAD

**Issue by jdrms** [ISCOUTB/AG-TalkHub#2]

**Comment by EmmanuelS23** [comment]
![Image](https://github.com/user-attachments/assets/2f6fc770-7bdc-4fa4-9ca1-098bb6ac8465)

**Comment by EmmanuelS23** [comment]
![Image](https://github.com/user-attachments/assets/4da20c6b-244b-4354-bedc-3c859b55d4fa)

**Comment by jairoserrano** [comment]
adelante
