### ISSUE TITLE
Elección de motor para SQL/NoSQL

### ISSUE THREAD

**Issue by jdrms** [ISCOUTB/AG-TalkHub#29]

**Comment by EmmanuelS23** [comment]
Para el desarrollo de este foro de discusión es necesario contar con una combinación de motores de bases de datos tanto relacionales como no relaciones. Cada uno de estos motores servirán para crear un sistema mas eficiente y flexible. 

**Motor Relacional (MySQL) para la Gestión de Usuarios, Contenido y Comentarios**
Pensamos utilizar el motor relacional MySQL el cual es ideal para manejar datos estructurados y relaciones complejas, esto será muy útil para manejar lo siguiente:

- Información de los usuarios: Nombre, correo electrónico y roles, que están claramente definidos y tienen relaciones específicas con otras entidades, como los hilos y comentarios.

- Contenido del foro: Los hilos de discusión, respuestas, y comentarios tienen una estructura bien definida que sirve para garantizar que las relaciones entre usuarios y sus publicaciones sean consistentes.

- Consultas avanzadas: MySQL permite ejecutar consultas complejas para filtrar hilos por popularidad, fecha, autor, o categoría.

**Motor NoSQL (MongoDB) para Documentos e Imágenes Adjuntos**
Un motor NoSQL es necesario para manejar datos no estructurados o semiestructurados, como:

- Documentos y archivos adjuntos: Los usuarios del foro pueden subir archivos, como imágenes, PDFs, y videos, que pueden variar mucho en tamaño y formato. NoSQL es flexible y escalable, ideal para almacenar este tipo de datos.

Integrar un motor relacional como no relacional en el foro es la mejor manera de aprovechar las fortalezas de cada tecnología. Mientras que MySQL garantiza la consistencia, integridad y eficiencia en la gestión de los datos estructurados como usuarios y publicaciones, NoSQL ofrece la flexibilidad y escalabilidad necesarias para manejar archivos adjuntos y documentos de forma eficiente.

**Comment by jairoserrano** [comment]
adelante
