### ISSUE TITLE
Revisar el esquema de datos

### ISSUE THREAD

**Issue by EmmanuelS23** [ISCOUTB/AG-TalkHub#31]

**Comment by Jcaro10** [comment]
[Modelado_TalkHub.pdf](https://github.com/user-attachments/files/16972196/Modelado_TalkHub.pdf)

Este modelo de datos para la Gestión del Foro. nos muestra de forma organizada las entidades que permiten la interacción entre usuarios, hilos de discusión, comentarios y categorías. Cada usuario está asociado a un rol específico y tiene la capacidad de crear hilos de discusión y comentarios. Los hilos se clasifican dentro de categorías específicas para facilitar la navegación y organización del contenido.

El modelo contempla la relación entre usuarios y sus contribuciones, permitiendo un seguimiento detallado de la actividad en el foro. Los usuarios pueden crear hilos de discusión, que a su vez contienen comentarios, formando una estructura jerárquica de conversación. Además, se incluye un sistema de votación para los comentarios, lo que fomenta la participación y la valoración del contenido por parte de la comunidad.

El modelo también incorpora la gestión de archivos adjuntos a los comentarios y un sistema de notificaciones, lo que enriquece la experiencia del usuario y mantiene a los participantes informados sobre la actividad relevante. Esto garantiza una plataforma de discusión integral, facilitando la administración efectiva del flujo de información y la interacción entre los usuarios del foro.

En cuanto a los pequeños cambios que se podrían realizar tenemos: Status (conectado, desconectado, ocupado), numero de vistas, sub-categorías, favoritos y este tipo de cosas que podemos implementar dentro de las entidades mencionadas anteriormente para diversificar la cantidad de información que se manejara. 

Actualizacion:
[Diagrama E-R talkhub.pdf](https://github.com/user-attachments/files/17051109/Diagrama.E-R.talkhub.pdf)
